Repository jonasbkarlsson/ev_smart_charging, pull requests merged in 2024-07, with the labels that each got.

#278 Fix config entry setup warning
  custom_components/ev_smart_charging/__init__.py
Labels: chore, patch, skip-changelog

#282 Revert "Fix config entry setup warning"
  custom_components/ev_smart_charging/__init__.py
Labels: chore, patch, skip-changelog

#283 Additional error messages.
  custom_components/ev_smart_charging/helpers/coordinator.py
Labels: chore, patch

#284 Added test cases.
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/helpers/config_flow.py
  custom_components/ev_smart_charging/helpers/coordinator.py
  tests/helpers/helpers.py
  tests/helpers/test_config_flow.py
  tests/helpers/test_price_adaptor.py
Labels: chore, patch, skip-changelog

#285 Handle price sensors with 15 minutes time resolution.
  custom_components/ev_smart_charging/helpers/coordinator.py
  tests/helpers/test_price_adaptor.py
  tests/price_15min.py
Labels: patch, skip-changelog

#288 Corrected updates of EV SOC Target.
  custom_components/ev_smart_charging/coordinator.py
Labels: bugfix, patch

#289 Fix.update_test_versions
  requirements_test311.txt
  requirements_test312.txt
  scripts/pytest_all_ha_versions_python312
  tests/README.md
Labels: chore, patch, skip-changelog

#290 Test HA 2024.7
  .devcontainer/devcontainer.json
  custom_components/ev_smart_charging/__init__.py
  requirements_dev.txt
  requirements_test.txt
  scripts/pytest_all_ha_versions_python312
  scripts/setup
  tests/coordinator/test_coordinator2.py
  tests/coordinator/test_coordinator_device_name.py
  tests/coordinator/test_coordinator_ev_connected.py
  tests/coordinator/test_coordinator_ev_controlled.py
  tests/coordinator/test_coordinator_keep_on2.py
  tests/coordinator/test_coordinator_keep_on3.py
  tests/coordinator/test_coordinator_keep_on4.py
  tests/coordinator/test_coordinator_opportunistic.py
  tests/coordinator/test_coordinator_opportunistic2.py
  tests/test_button.py
  tests/test_init.py
  tests/test_number.py
  tests/test_select.py
  tests/test_sensor.py
  tests/test_switch.py
Labels: chore, patch, skip-changelog

#291 Corrected HA version check.
  custom_components/ev_smart_charging/__init__.py
  tests/coordinator/test_coordinator_device_name.py
Labels: chore, patch, skip-changelog

#292 Update readme.
  README.md
Labels: chore, patch, skip-changelog

#300 Remove support of reconfiguration for HA 2024.7
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/config_flow.py
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/translations/en.json
  scripts/pytest_all_ha_versions_python312
Labels: bugfix, patch

#301 Update dev environment
  .devcontainer/hass/.gitignore
  .gitignore
  .vscode/launch.json
  config/configuration.yaml
  requirements_dev.txt
  requirements_test.txt
  scripts/develop
Labels: chore, patch, skip-changelog
