Repository jonasbkarlsson/ev_smart_charging, pull requests merged in 2024-08, with the labels that each got.

#303 Enable reconfiguration for HA 2024.7
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/config_flow.py
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/translations/en.json
  requirements_dev.txt
  requirements_test.txt
  scripts/pytest_all_ha_versions_python312
  tests/test_init.py
Labels: bugfix, patch

#304 Change name of lock.
  custom_components/ev_smart_charging/__init__.py
Labels: patch, skip-changelog

#305 Fixed sync of integration and device name for HA 2024.7.
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/coordinator.py
  tests/test_init.py
Labels: bugfix, patch, skip-changelog

#306 Added Dutch, Norwegian and Swedish translations.
  .github/workflows/pre-release.yml
  .github/workflows/pull.yml
  .github/workflows/push.yml
  custom_components/ev_smart_charging/button.py
  custom_components/ev_smart_charging/const.py
  custom_components/ev_smart_charging/entity.py
  custom_components/ev_smart_charging/number.py
  custom_components/ev_smart_charging/select.py
  custom_components/ev_smart_charging/sensor.py
  custom_components/ev_smart_charging/switch.py
  custom_components/ev_smart_charging/translations/en.json
  custom_components/ev_smart_charging/translations/nb.json
  custom_components/ev_smart_charging/translations/nl.json
  custom_components/ev_smart_charging/translations/sv.json
  hacs.json
  scripts/pytest_all_ha_versions_python310
  scripts/pytest_all_ha_versions_python311
  scripts/pytest_all_ha_versions_python39
  tests/test_sensor.py
Labels: chore, minor, translation

#311 No translation for entity ID.
  custom_components/ev_smart_charging/button.py
  custom_components/ev_smart_charging/entity.py
  custom_components/ev_smart_charging/number.py
  custom_components/ev_smart_charging/select.py
  custom_components/ev_smart_charging/sensor.py
  custom_components/ev_smart_charging/switch.py
  scripts/pytest_all_ha_versions_python311
  tests/test_button.py
  tests/test_number.py
  tests/test_select.py
  tests/test_switch.py
Labels: bugfix, patch

#314 Reset keep_on state if target SOC is updated.
  custom_components/ev_smart_charging/coordinator.py
  tests/coordinator/test_coordinator_keep_on4.py
Labels: bugfix, patch

#315 Avoid turning on charger during intialization.
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/coordinator.py
  tests/conftest.py
Labels: bugfix, patch

#316 Avoid turning on charger during intialization.
  custom_components/ev_smart_charging/coordinator.py
Labels: bugfix, patch, skip-changelog

#317 Updated readme.
  README.md
Labels: chore, major, skip-changelog

#318 Add danish translation
  custom_components/ev_smart_charging/translations/da.json
Labels: translation

#323 Create FUNDING.yml
  .github/FUNDING.yml
Labels: chore, skip-changelog
