Repository jonasbkarlsson/ev_smart_charging, pull requests merged in 2025-01, with the labels that each got.

#342 Fixed typos and adjusted for uniformity
  custom_components/ev_smart_charging/translations/da.json
Labels: minor, translation

#352 Changed Entso-e entity name.
  README.md
Labels: chore, minor

#354 Added async_setup_entry.
  tests/coordinator/test_coordinator.py
  tests/coordinator/test_coordinator_keep_on.py
  tests/coordinator/test_coordinator_keep_on2.py
  tests/coordinator/test_coordinator_late_ready.py
  tests/coordinator/test_coordinator_low_price_charging.py
  tests/coordinator/test_coordinator_low_soc_charging.py
  tests/coordinator/test_coordinator_negative_price.py
  tests/coordinator/test_coordinator_no_ready.py
  tests/coordinator/test_coordinator_reschedule.py
  tests/coordinator/test_coordinator_start_hour_both_same.py
  tests/coordinator/test_coordinator_start_hour_end_before_start.py
  tests/coordinator/test_coordinator_start_hour_only_start.py
  tests/coordinator/test_coordinator_start_hour_start_before_end.py
Labels: minor, skip-changelog

#355 Removed unused imports. Updated name of entso-e sensor.
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/config_flow.py
  custom_components/ev_smart_charging/helpers/config_flow.py
  tests/helpers/helpers.py
Labels: minor, skip-changelog

#356 Treat electricity_price platform as nordpool platform.
  custom_components/ev_smart_charging/helpers/general.py
Labels: minor

#357 Don't set config_entry.
  custom_components/ev_smart_charging/config_flow.py
Labels: minor, skip-changelog

#359 Usage of price sensor state and attribute current_price removed.
  custom_components/ev_smart_charging/helpers/price_adaptor.py
  tests/helpers/test_price_adaptor.py
Labels: minor, skip-changelog

#361 Config flow version 7.
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/config_flow.py
  custom_components/ev_smart_charging/const.py
Labels: minor, skip-changelog

#362 Support any compatible price integration.
  README.md
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/helpers/coordinator.py
  custom_components/ev_smart_charging/helpers/general.py
  custom_components/ev_smart_charging/helpers/price_adaptor.py
  tests/helpers/helpers.py
  tests/helpers/test_config_flow.py
  tests/helpers/test_coordinator.py
  tests/helpers/test_general.py
  tests/helpers/test_price_adaptor.py
  tests/price.py
  tests/test_number.py
Labels: enhancement, minor

#364 Update description of number.ev_smart_charging_minimum_ev_soc
  README.md
Labels: patch, skip-changelog

#365 Reduce number of error messages.
  custom_components/ev_smart_charging/coordinator.py
Labels: patch

#367 Support Input Boolean and switches without unique id.
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/helpers/config_flow.py
Labels: minor

#370 Updates for HA 2025.1
  scripts/pytest_all_ha_versions_python313
  tests/test_config_flow.py
Labels: patch, skip-changelog

#372 Update for the HA Nord Pool integration.
  README.md
Labels: documentation

#373 Added another variant of opportunistic charging.
  custom_components/ev_smart_charging/const.py
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/number.py
  custom_components/ev_smart_charging/sensor.py
  custom_components/ev_smart_charging/switch.py
  custom_components/ev_smart_charging/translations/en.json
  tests/coordinator/test_coordinator_opportunistic_type2.py
  tests/coordinator/test_coordinator_opportunistic_type2_2.py
  tests/price.py
Labels: enhancement, minor

#376 Support price integration with prices in one attribute.
  custom_components/ev_smart_charging/helpers/coordinator.py
  custom_components/ev_smart_charging/helpers/price_adaptor.py
  tests/helpers/test_coordinator.py
Labels: patch

#380 Changed to 15 minutes price and charging resolution.
  custom_components/ev_smart_charging/__init__.py
  custom_components/ev_smart_charging/const.py
  custom_components/ev_smart_charging/coordinator.py
  custom_components/ev_smart_charging/helpers/coordinator.py
  custom_components/ev_smart_charging/helpers/general.py
  custom_components/ev_smart_charging/select.py
  custom_components/ev_smart_charging/sensor.py
  custom_components/ev_smart_charging/translations/da.json
  custom_components/ev_smart_charging/translations/en.json
  custom_components/ev_smart_charging/translations/nb.json
  custom_components/ev_smart_charging/translations/nl.json
  custom_components/ev_smart_charging/translations/sv.json
  tests/conftest.py
  tests/const.py
  tests/coordinator/const.py
  tests/coordinator/test_coordinator.py
  tests/coordinator/test_coordinator_ev_connected.py
  tests/coordinator/test_coordinator_keep_on.py
  tests/coordinator/test_coordinator_keep_on2.py
  tests/coordinator/test_coordinator_keep_on4.py
  tests/coordinator/test_coordinator_late_ready.py
  tests/coordinator/test_coordinator_negative_price.py
  tests/coordinator/test_coordinator_no_ready.py
  tests/coordinator/test_coordinator_opportunistic2.py
  tests/coordinator/test_coordinator_opportunistic_type2_2.py
  tests/coordinator/test_coordinator_reschedule.py
  tests/coordinator/test_coordinator_start_hour_both_same.py
  tests/coordinator/test_coordinator_start_hour_end_before_start.py
  tests/coordinator/test_coordinator_start_hour_only_start.py
  tests/coordinator/test_coordinator_start_hour_start_before_end.py
  tests/coordinator/test_coordinator_status.py
  tests/helpers/test_coordinator.py
  tests/helpers/test_general.py
  tests/helpers/test_price_adaptor.py
  tests/price.py
  tests/price_15min.py
  tests/test_daylight_saving.py
  tests/test_init.py
  tests/test_select.py
  tests/test_sensor.py
Labels: enhancement, minor

#381 Revert sensor attribute to number of hours.
  custom_components/ev_smart_charging/sensor.py
  custom_components/ev_smart_charging/translations/en.json
  tests/test_sensor.py
Labels: patch, skip-changelog

#368 Documentation/translation: Updates for release v2.3.0
  README.md
  custom_components/ev_smart_charging/translations/da.json
  custom_components/ev_smart_charging/translations/en.json
  custom_components/ev_smart_charging/translations/nb.json
  custom_components/ev_smart_charging/translations/nl.json
  custom_components/ev_smart_charging/translations/sv.json
Labels: chore, translation

#384 fix: Add _unrecorded_attributes to EVSmartChargingSensorCharging
  custom_components/ev_smart_charging/sensor.py
Labels: bugfix, patch

#386 Correction of non-continuous scheduling.
  custom_components/ev_smart_charging/helpers/coordinator.py
Labels: bugfix, patch
